steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/models-rj-sms-api:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/models-rj-sms-api:$COMMIT_SHA']
  # Kustomize: set the image in the kustomization.yaml file
  - name: 'gcr.io/cloud-builders/gke-deploy'
    dir: 'k8s/prod'
    entrypoint: 'kustomize'
    args:
      - 'edit'
      - 'set'
      - 'image'
      - 'gcr.io/project-id/models-rj-sms-api=gcr.io/$PROJECT_ID/models-rj-sms-api:$COMMIT_SHA'
  # Kustomize: apply the kustomization.yaml file
  - name: 'gcr.io/cloud-builders/gke-deploy'
    dir: 'k8s/prod'
    entrypoint: 'kustomize'
    args: ['build', '.', '-o', 'prod.yaml']
  # Deploy the application to the GKE cluster
  - name: 'gcr.io/cloud-builders/gke-deploy'
    dir: 'k8s/prod'
    args:
      - 'run'
      - '--filename=prod.yaml'
      - '--location=us-central1'
      - '--cluster=datalake'
      - '--project=rj-sms'

images:
  - 'gcr.io/$PROJECT_ID/models-rj-sms-api:$COMMIT_SHA'
