---
# API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: models-rj-sms-staging
  namespace: models-rj-sms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: models-rj-sms-staging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: models-rj-sms-staging
    spec:
      containers:
        - name: models-rj-sms
          image: gcr.io/project-id/models-rj-sms
          envFrom:
            - secretRef:
                name: models-rj-sms-staging-secrets
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 500m
              memory: 2Gi
          command: ["/bin/bash", "/compose-entrypoint.sh"]
          livenessProbe:
            httpGet:
              path: /misc/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /misc/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: models-rj-sms-staging
  name: models-rj-sms-staging
  namespace: models-rj-sms
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: models-rj-sms-staging

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: models-rj-sms-staging
  namespace: models-rj-sms
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - staging.models-rj-sms.dados.rio
      secretName: models-rj-sms-staging-tls
  rules:
    - host: staging.models-rj-sms.dados.rio
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: models-rj-sms-staging
                port:
                  number: 80

# ---
# # Horizontal Pod Autoscaler (HPA) baseado em uso de CPU
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: models-rj-sms-staging-hpa
#   namespace: models-rj-sms
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: models-rj-sms-staging
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50
